version: '3.8'
services:
  redis:
    image: redis:alpine3.20
    container_name: internet-banking-redis
    ports:
      - "5260:6379"
    volumes:
      - redis-data:/data
    restart: always
volumes:
  redis-data: