server:
  port: 8000
redis:
  port: 5260
  host: localhost
spring:
  application:
   name: internet-banking
  datasource:
    url: jdbc:mysql://localhost:3306/internet_banking?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
security:
  keys:
    string-hash:
      private-path: keys/string-hash-private.key
      public-path: keys/string-hash-public.key
    access-token:
      private-path: keys/access-token-private.key
      public-path: keys/access-token-public.key